apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: muru-app
  namespace: murugesan
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
