apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-k8s-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: dev
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

