
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: r1
  name: ds
spec:
  selector:
    matchLabels:
      app: r1
  template:
    metadata:
      labels:
        app: r1
    spec:
      containers:
      - image: httpd
        name: httpd
        resources:
          limits:
            cpu: 40m
            memory: 40Mi
          requests:
            cpu: 20m
            memory: 20Mi
